[package]
name = "aether-capture"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = "0.14.0"

[[example]]
name = "x11_list_sources_probe"
path = "examples/x11_list_sources_probe.rs"

[[example]]
name = "x11_capture_frame_probe"
path = "examples/x11_capture_frame_probe.rs"

[[example]]
name = "x11_continuous_capture_probe"
path = "examples/x11_continuous_capture_probe.rs"
